# Generated by Django 3.2.4 on 2021-06-13 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstLine', models.CharField(max_length=100)),
                ('SecondLine', models.CharField(blank=True, max_length=100)),
                ('Town', models.CharField(max_length=100)),
                ('County', models.CharField(max_length=50)),
                ('PostCode', models.CharField(max_length=7)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary', models.TextField(blank=True)),
                ('phone', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('RSVP', models.IntegerField(choices=[(0, 'I can attend the ceremony and the dinner'), (1, 'I can attend only the ceremony'), (2, 'I cannot attend')], help_text='Please select your availability on the day of the wedding')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
