# Generated by Django 3.2.4 on 2021-09-18 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(blank=True, max_length=100, verbose_name='First line')),
                ('second_line', models.CharField(blank=True, max_length=100, verbose_name='Second line')),
                ('town', models.CharField(blank=True, max_length=100, verbose_name='Town')),
                ('county', models.CharField(blank=True, max_length=50, verbose_name='County')),
                ('postcode', models.CharField(blank=True, help_text="e.g. 'BT69 420'", max_length=8, verbose_name='Postcode')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary', models.TextField(blank=True, help_text='Please enter your dietary requirements or allergies', verbose_name='Dietary requirements')),
                ('phone', models.CharField(max_length=15, verbose_name='Mobile phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('RSVP', models.IntegerField(choices=[(0, 'I can attend the ceremony and the dinner'), (1, 'I can attend only the ceremony'), (2, 'I cannot attend')], help_text='Please select your availability on the day of the wedding', verbose_name='Attendance selection')),
                ('song', models.TextField(blank=True, help_text='Suggest song(s) to be played at the evening party', verbose_name='Song recommendations')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address', verbose_name='Postal address')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
