# Generated by Django 3.2.4 on 2021-09-18 23:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dietary',
            field=models.TextField(blank=True, help_text="Please enter your dietary requirements or allergies. Enter 'None' if not", verbose_name='Dietary requirements'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text="e.g.'+447889016685'", max_length=128, region=None, verbose_name='Mobile phone number'),
        ),
    ]
