# Generated by Django 3.2.4 on 2021-09-20 23:21

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210918_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='consent_given',
            field=models.BooleanField(default=0, verbose_name='I consent to my data being stored in line with the privacy policy'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='RSVP',
            field=models.IntegerField(choices=[(0, 'I can attend the ceremony and the dinner'), (1, 'I can attend only the ceremony'), (2, 'I cannot attend')], help_text='Please select your availability on the day of the wedding. Mobile users: long press your selection', verbose_name='Attendance selection (*)'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text="Phone number must be in international format e.g.'+447889016685'", max_length=128, region=None, verbose_name='Mobile phone number (*)'),
        ),
    ]
