# Generated by Django 3.2.4 on 2021-06-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='PostCode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='guest',
            name='dietary',
            field=models.TextField(blank=True, help_text='Please enter your dietary requirements or allergies'),
        ),
    ]
