# Generated by Django 3.2.4 on 2021-06-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210613_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.address'),
        ),
    ]
