# Generated by Django 3.2.4 on 2021-06-16 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_guest_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.address'),
        ),
    ]
