# Generated by Django 3.2.4 on 2021-12-06 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211206_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address', verbose_name='Postal address'),
        ),
    ]
