# Generated by Django 3.2.4 on 2021-06-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210617_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='County',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='FirstLine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='PostCode',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='address',
            name='Town',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
